[package]
name = "simplenn"
version = "0.1.0"
authors = ["jinpu"]

[dependencies]
rand = "0.4"
[dependencies.accel]
git = "https://github.com/termoshtt/accel.git"
[dependencies.accel-derive]
version = "0.1.0"
git = "https://github.com/termoshtt/accel.git"