[package]
name = "simplenn"
version = "0.1.0"
authors = ["jinpu"]

[dependencies]
rand = "0.4"
[dependencies.accel]
path = "F:\\source\\Rust\\accel"
[dependencies.accel-derive]
path = "F:\\source\\Rust\\accel\\accel-derive"